name: npm-publish
on:
  push:
    branches:
      - master # Change this to your default branch
jobs:
  npm-publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - name: Upload to Amazon S3
        uses: Noelware/s3-action@master # this can be `master` or a tagged release
        with:
            directories: |
                ./v1,
            access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
            # path-format: '/$(tag)'
            secret-key: ${{ secrets.S3_SECRET_KEY }}
            prefix: /v1
            # region: us-east-1
            bucket: ${{ secrets.S3_BUCKET_NAME }}
